name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      test_scope: ${{ steps.detect.outputs.test_scope }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Analyze changes
        id: detect
        run: |
          echo "=== Step 1: Scanning repository ==="
          echo "Looking for all paths in frontend/apps/ and backend/apps/"
          ALL_PATHS=$(find . -type f \( -path "./frontend/apps/*" -o -path "./backend/apps/*" \) | sed 's|^./||')
          echo "Found paths:"
          echo "$ALL_PATHS"
          
          echo "=== Step 2: Extracting unique service paths ==="
          SERVICES=$(echo "$ALL_PATHS" | grep -E "^(frontend|backend)/apps/" | cut -d'/' -f3 | sort -u)
          echo "Detected services:"
          echo "$SERVICES"

          echo "=== Step 3: Getting changed files ==="
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            SHA="${{ github.event.pull_request.head.sha }}"
          else
            SHA="${{ github.sha }}"
          fi
          echo "Using SHA: $SHA"
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r $SHA)
          echo "All changed files:"
          echo "$CHANGED_FILES"
          
          echo "=== Step 4: Matching changes with services ==="
          MATCHES=""
          for service in $SERVICES; do
            if echo "$CHANGED_FILES" | grep -qE "^(frontend|backend)/apps/$service/"; then
              echo "Found changes in service: $service"
              MATCHES="$MATCHES $service"
            fi
          done

          echo "=== Step 5: Preparing result ==="
          RESULT=${MATCHES## }
          RESULT=${RESULT// /,}
          echo "Final test scope: ${RESULT:-empty (will run all tests)}"
          echo "test_scope=$RESULT" >> $GITHUB_OUTPUT

  setup:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

  all-tests:
    needs: [detect-changes, setup]
    if: needs.detect-changes.outputs.test_scope == ''
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0
    steps:
      - uses: actions/checkout@v4
      - name: Run all tests
        run: npx playwright test

  selective-tests:
    needs: [detect-changes, setup]
    if: needs.detect-changes.outputs.test_scope != ''
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0
    steps:
      - uses: actions/checkout@v4
      - name: Run selective tests
        run: npx playwright test --grep "@${{ needs.detect-changes.outputs.test_scope }}" 