name: Main CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    uses: ./.github/workflows/e2e-with-changes.yml
    with:
      pr_sha: ${{ github.event.pull_request.head.sha || github.sha }} 